### ISSUE TITLE
Subtitle missing font file

### ISSUE THREAD

**Issue by hyz2993** [ClairMeta/ClairMeta#218]
Hi there! Happy new year! 
We met and WindowsOS only Error for a DCP version file.
```
python -m clairmeta.cli check -type dcp Z:\sips\2022\November\oe22270\4b3d8381-44e4-4b3d-8ed3-aca85ae5a032\objects\IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF
......
Error(s):
  + cpl_b28d5c41-5207-4c11-ae7a-708066a3a810.xml (IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF)
    + sub_c815d7f9-446e-4c97-985d-fd75fa7bbab9.mxf
      . Subtitle font file exists.
        Subtitle missing font file : 2d0fb9f5-07b8-434a-881b-c808aabd9dd4
```
The interesting thing is the result of the same object tested on a Mac returns 'check succeed'
I noticed clairmeta may create an temp file which is named with that numebr 2d0fb9f5-07b8-434a-881b-c808aabd9dd4 (full path C:\Users\Ingest_1\AppData\Local\Temp\tmp3xib6_4x\2d0fb9f5-07b8-434a-881b-c808aabd9dd4)

Do you have any advice on it? Thanks!

**Comment by hyz2993** [comment]
The full cmd data will be
```
C:\Users\Ingest_1>python -m clairmeta.cli check -type dcp Z:\sips\2022\November\oe22270\4b3d8381-44e4-4b3d-8ed3-aca85ae5a032\objects\IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF
2023-01-10 11:56:37,204 - Clairmeta - WARNING - Missing dependency : sox.exe
2023-01-10 11:56:37,221 - Clairmeta - INFO - Probing DCP : Z:\sips\2022\November\oe22270\4b3d8381-44e4-4b3d-8ed3-aca85ae5a032\objects\IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF
2023-01-10 11:56:37,383 - Clairmeta - INFO - Total time : 0.16 seconds
2023-01-10 11:56:37,549 - Clairmeta - INFO - Checking DCP : Z:\sips\2022\November\oe22270\4b3d8381-44e4-4b3d-8ed3-aca85ae5a032\objects\IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF
2023-01-10 11:56:37,710 - Clairmeta - WARNING - b'Program stopped on error.\r\nFile open failure.\r\n'
folder: C:\Users\Ingest_1\AppData\Local\Temp\tmp3xib6_4x
path: C:\Users\Ingest_1\AppData\Local\Temp\tmp3xib6_4x\2d0fb9f5-07b8-434a-881b-c808aabd9dd4
uri: 2d0fb9f5-07b8-434a-881b-c808aabd9dd4
// The returns above are the add-ons I put to check the full path
2023-01-10 11:56:38,542 - Clairmeta - INFO - Check report:

Status : Fail
Path : Z:\sips\2022\November\oe22270\4b3d8381-44e4-4b3d-8ed3-aca85ae5a032\objects\IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF
Size : 618.24 kiB
Total check : 122
Total time : 0.96 sec

Warning(s):
  + cpl_b28d5c41-5207-4c11-ae7a-708066a3a810.xml (IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF)
    . Digital Cinema Naming Convention compliance (9.3).
      ContentTitle should have 12 parts to be fully compliant with ISDCF naming convention version 9.6, 9 part(s) found
      Field TerritoryRating not found in ContentTitle
      Field Studio not found in ContentTitle
      Field Facility not found in ContentTitle
    . Captions (presence) from CPL and ContentTitleText shall match.
      ContentTitle suggest OCAP but CPL has none
    + 82cf8e51-747b-44e9-a896-26e82581602d
      . CPL assets referencing external package.
        Asset missing (Picture), external reference
    + d3ead528-6360-4e34-8d59-8388442b32fb
      . CPL assets referencing external package.
        Asset missing (Sound), external reference
Error(s):
  + cpl_b28d5c41-5207-4c11-ae7a-708066a3a810.xml (IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF)
    + sub_c815d7f9-446e-4c97-985d-fd75fa7bbab9.mxf
      . Subtitle font file exists.
        Subtitle missing font file : 2d0fb9f5-07b8-434a-881b-c808aabd9dd4

DCP - Z:\sips\2022\November\oe22270\4b3d8381-44e4-4b3d-8ed3-aca85ae5a032\objects\IMUSTWAY_FTR_F_EN-EN-OCAP_51_2K_20221127_SMPTE_VF - Check failed
```

There were another ERROR about the encoding problem
```
. Subtitle XML file syntax and structure validation.
        . ClairMeta internal error
        Traceback (most recent call last):
          File "C:\Users\Ingest_1\AppData\Local\Programs\Python\Python310\lib\site-packages\clairmeta\dcp_check.py", line 140, in run_check
            check_res = check(*args)
          File "C:\Users\Ingest_1\AppData\Local\Programs\Python\Python310\lib\site-packages\clairmeta\dcp_check_subtitle.py", line 266, in check_subtitle_cpl_xml
            check_xml(self, path, namespace, label, self.dcp.schema)
          File "C:\Users\Ingest_1\AppData\Local\Programs\Python\Python310\lib\site-packages\clairmeta\dcp_check_utils.py", line 68, in check_xml
            check_xml_constraints(checker, xml_path)
          File "C:\Users\Ingest_1\AppData\Local\Programs\Python\Python310\lib\site-packages\clairmeta\dcp_check_utils.py", line 46, in check_xml_constraints
            xml_file = file.read()
          File "C:\Users\Ingest_1\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
            return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 70725: character maps to <undefined>
```
For this one I temp changed `with open(xml_path) as file:` to  `with open(xml_path,encoding='utf8') as file:`  in dcp_check_utils.py though I assume cp1252 should be the correct one for the xml. "

**Comment by remia** [comment]
Hi @hyz2993,

The first error is indeed a false positive on Windows, I think it's due to asdcp-unwrap having issue to extract the font file from the SMPTE MXF subtitles, we rely on that for some checks. In our internal unit tests we ignore some tests on Windows for that reason https://github.com/Ymagis/ClairMeta/blob/develop/tests/test_dcp_check.py#L81. I'm not sure yet what's the best way to handle that while it's not fixed, maybe add a note in the check error message when run on Windows.

For the second error, could you share the XML privately?

**Comment by hyz2993** [comment]
Thanks @remia ! I have contact you via Linkedin to send XML thanks.

**Comment by remia** [comment]
Thanks @hyz2993, I'll include the encoding fix as it's a valid point and we should force UTF-8 on Windows, we already do it in https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/utils/xml.py#L198 but this use was missed.

I guess I'll live the issue open as the missing font file bug is for the time being out of our control I think but it's good to have visibility on the issue.

**Comment by hyz2993** [comment]
Thanks for following up! Looking forward to the update!
